Repository insightsengineering/teal.reporter, pull requests merged in 2022-07, with the labels that each got.

#80 6 archive@main
  NEWS.md
  R/Archiver.R
  R/FileBlock.R
  R/PictureBlock.R
  R/Renderer.R
  R/ReportCard.R
  R/Reporter.R
  R/TableBlock.R
  R/TextBlock.R
  man/Archiver.Rd
  man/FileArchiver.Rd
  man/FileBlock.Rd
  man/JSONArchiver.Rd
  man/PictureBlock.Rd
  man/ReportCard.Rd
  man/Reporter.Rd
  man/TableBlock.Rd
  man/TealReportCard.Rd
  man/TextBlock.Rd
  tests/testthat/test-Archiver.R
  tests/testthat/test-FileBlock.R
  tests/testthat/test-PictureBlock.R
  tests/testthat/test-ReportCard.R
  tests/testthat/test-Reporter.R
  tests/testthat/test-TableBlock.R
  tests/testthat/test-TextBlock.R
Labels: core

#84 Update staged_dependencies.yaml
  staged_dependencies.yaml
Labels: core

#97 append_fs accepts a list
  NEWS.md
  R/TealReportCard.R
  man/TealReportCard.Rd
  tests/testthat/test-TealReportCard.R
Labels: core, blocked

#101 append_plot - grid::grid.draw for trellis
  NEWS.md
  R/PictureBlock.R
  inst/WORDLIST
Labels: core

#100 optional height and width arguments to the append_plot method
  NEWS.md
  R/ReportCard.R
  man/ReportCard.Rd
  tests/testthat/test-PictureBlock.R
  tests/testthat/test-ReportCard.R
Labels: core

#102 update README
  README.md
Labels: core

#109 Update installation instructions
  README.md
Labels: core

#104 update staged.deps
  staged_dependencies.yaml
Labels: core

#110 Handle report generation for CI
  tests/testthat.R
Labels: core

#108 try render and check for pdflatex
  DESCRIPTION
  R/DownloadModule.R
  R/Previewer.R
  man/download_report_button_srv.Rd
Labels: core

#114 staged deps for teal.osprey
  staged_dependencies.yaml
Labels: core

#113 update reporter + staged.deps
  NEWS.md
  R/PictureBlock.R
  staged_dependencies.yaml
Labels: core

#116 add staged.deps
  staged_dependencies.yaml
Labels: core

#119 update append_fs
  R/TealReportCard.R
  man/TealReportCard.Rd
  tests/testthat/test-TealReportCard.R
Labels: core

#123 Update font awesome icon labels for FA 6
  R/Previewer.R
Labels: enhancement

#121 120 append fs title@main
  R/TealReportCard.R
  man/TealReportCard.Rd
  tests/testthat/test-TealReportCard.R
Labels: core

#122 css and buttons
  R/AddCardModule.R
  R/DownloadModule.R
  R/Previewer.R
  R/ResetModule.R
  R/SimpleReporter.R
  inst/css/Previewer.css
  inst/css/SimpleReporter.css
  inst/css/custom.css
  man/reporter_previewer_srv.Rd
  man/reset_report_button_ui.Rd
  tests/testthat/test-SimpleReporter.R
  vignettes/previewerReporter.Rmd
  vignettes/simpleReporter.Rmd
  vignettes/teal.reporter.Rmd
Labels: core
